os:
  - linux
  - osx

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy2.7"
  - "pypy3.5"

before_install:
  - pip install codecov

install:
  - python setup.py install

script:
  - coverage run setup.py test

after_success:
  - codecov