language: python

matrix:
  include:
    - os: linux
      python: 2.7
      env: PY=py27
    - os: linux
      python: 3.4
      env: PY=py34
    - os: linux
      python: 3.5
      env: PY=py35
    - os: linux
      python: 3.6
      env: PY=py36
    - os: osx
      language: generic
      env: PY=py27
    - os: osx
      language: generic
      env: PY=py36

install:
  - ./.travis/install.sh

script:
  - coverage run -m unittest discover -t ./ -s sshx/tests

after_success:
  - codecov